INSERT INTO TB_CATEGORY(NAME) VALUES ('Livros');
INSERT INTO TB_CATEGORY(NAME) VALUES ('Eletrônicos');
INSERT INTO TB_CATEGORY(NAME) VALUES ('Computadores');
INSERT INTO TB_CATEGORY(NAME) VALUES ('Smartphoones');
